// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZV7JrXS2kvJGCp3feyA_94Qgt2ZAm-4',
    appId: '1:311244481421:web:047d380631ec68d3e753c4',
    messagingSenderId: '311244481421',
    projectId: 'studyapp-a542b',
    authDomain: 'studyapp-a542b.firebaseapp.com',
    storageBucket: 'studyapp-a542b.firebasestorage.app',
    measurementId: 'G-69V1MCJMVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwr7ywZVGkmuY-A4oMknla1N1htUJ7jXs',
    appId: '1:311244481421:android:7af7e8c4160df28ee753c4',
    messagingSenderId: '311244481421',
    projectId: 'studyapp-a542b',
    storageBucket: 'studyapp-a542b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0c7qnGebidX8rcaG9nYkvxElmWeLEyo',
    appId: '1:311244481421:ios:123d62b3512db34de753c4',
    messagingSenderId: '311244481421',
    projectId: 'studyapp-a542b',
    storageBucket: 'studyapp-a542b.firebasestorage.app',
    iosBundleId: 'com.example.studyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0c7qnGebidX8rcaG9nYkvxElmWeLEyo',
    appId: '1:311244481421:ios:123d62b3512db34de753c4',
    messagingSenderId: '311244481421',
    projectId: 'studyapp-a542b',
    storageBucket: 'studyapp-a542b.firebasestorage.app',
    iosBundleId: 'com.example.studyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLZV7JrXS2kvJGCp3feyA_94Qgt2ZAm-4',
    appId: '1:311244481421:web:fcd79aedafe243a1e753c4',
    messagingSenderId: '311244481421',
    projectId: 'studyapp-a542b',
    authDomain: 'studyapp-a542b.firebaseapp.com',
    storageBucket: 'studyapp-a542b.firebasestorage.app',
    measurementId: 'G-FCT01P5X8K',
  );
}
